#!/usr/bin/env bash
set -euo pipefail

# session-end-handoff.sh — Power Engineer SessionEnd hook (v1.4.0 Tier 2 memory)
#
# Purpose: Automatically capture a session handoff summary when Claude Code
# fires the SessionEnd event. Part of the 3-tier memory architecture:
#   - Tier 1 (reliability): CLAUDE.md proactive memory rules (always runs)
#   - Tier 2 (automation):  this hook (best-effort — may skip /exit + /clear)
#   - Tier 3 (explicit):    /power-engineer save-phase flow
#
# Hook contract:
#   - Best-effort per GitHub issues #17885 (/exit) and #6428 (/clear).
#   - Exits 0 on every path; error diagnostics are routed to memory-errors.log
#     so session termination is never blocked or delayed.
#   - Uses CLAUDE_PROJECT_DIR (populated by Claude Code) to locate the project.

# ── Resolve project root ─────────────────────────────────────────────────────
# CLAUDE_PROJECT_DIR is set by Claude Code at hook invocation. Fall back to the
# current working directory if the var is unset (e.g., during manual testing).
project_dir="${CLAUDE_PROJECT_DIR:-$PWD}"
state_dir="${project_dir}/.power-engineer"
error_log="${state_dir}/memory-errors.log"
script_name="session-end-handoff.sh"

# ── Error sink ───────────────────────────────────────────────────────────────
# Append errors to memory-errors.log with ISO-8601 UTC timestamp. `mkdir -p`
# runs first so the log dir exists even if state_dir was missing.
log_error() {
    # All stderr is silenced at the block level because bash reports redirection
    # failures (e.g., "Not a directory" when $state_dir exists as a regular
    # file) before the command runs, so per-command `2>/dev/null` is not
    # sufficient. The hook is best-effort; failing to log a failure is OK.
    {
        local message="$1"
        local ts
        ts="$(date -u +%Y-%m-%dT%H:%M:%SZ || echo 'timestamp-unavailable')"
        mkdir -p "$state_dir" || true
        printf '[%s] %s: %s\n' "$ts" "$script_name" "$message" >> "$error_log" || true
    } 2>/dev/null || true
}

# Trap any unhandled error → log it → exit 0 (SessionEnd must never block exit)
trap 'log_error "unhandled error on line $LINENO (exit_code=$?)"; exit 0' ERR
trap 'exit 0' EXIT

# ── Collect handoff fields (each with its own fallback) ──────────────────────
timestamp_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo 'unknown')"
timestamp_filename="$(date -u +%Y%m%dT%H%M%SZ 2>/dev/null || echo 'unknown')"

# Git-dependent fields: each field falls back to a placeholder if git is
# unavailable or the cwd is not a git repo. Each command runs inside a
# subshell so `cd` does not affect the outer script, and the `|| echo`
# fallback keeps set -e happy on failure.
git_field() {
    # Usage: git_field <fallback> -- <git-args...>
    # Runs `git <args>` inside a subshell at $project_dir; prints <fallback>
    # on any failure.
    local fallback="$1"
    shift
    # Subshell: cd into project_dir and run git. On any failure, print fallback.
    ( cd "$project_dir" && git "$@" ) 2>/dev/null || printf '%s\n' "$fallback"
}

branch_name="$(git_field 'unknown' branch --show-current)"
recent_commits="$(git_field 'unavailable' log -5 --oneline)"
# `head -20` runs in the outer subshell so its non-zero exit on an empty
# pipeline input is harmless; modified_files stays 'unavailable' on git failure.
modified_files="$(git_field 'unavailable' status --porcelain | head -20)"

# ── Ensure state dir ─────────────────────────────────────────────────────────
if ! mkdir -p "$state_dir" 2>/dev/null; then
    log_error "failed to create state dir: $state_dir"
    exit 0
fi

# ── Write handoff file ───────────────────────────────────────────────────────
# Use a grouped-redirection block (printf calls writing to the file) instead of
# a $(cat <<EOF) command substitution. The block avoids heredoc parser quirks
# around apostrophes in prose, keeps variable expansion explicit, and is
# ShellCheck-friendly.
handoff_file="${state_dir}/session-handoff-${timestamp_filename}.md"

if ! {
    printf '# Session Handoff — %s\n\n' "$timestamp_iso"
    printf 'Generated automatically by the SessionEnd hook.\n\n'
    printf '## Context\n\n'
    printf -- '- **Timestamp (UTC):** %s\n' "$timestamp_iso"
    printf -- '- **Branch:** %s\n' "$branch_name"
    printf -- '- **Project directory:** %s\n\n' "$project_dir"
    printf '## Recent commits (last 5)\n\n'
    # shellcheck disable=SC2016  # backticks are literal markdown code-fence markers, not command substitution
    printf '```\n%s\n```\n\n' "$recent_commits"
    printf '## Modified files (first 20 from git status)\n\n'
    # shellcheck disable=SC2016  # backticks are literal markdown code-fence markers, not command substitution
    printf '```\n%s\n```\n\n' "$modified_files"
    printf '## Next steps\n\n'
    printf '<!-- Fill in when reviewing this handoff. What was in progress?\n'
    printf '     What is the next action? Any blockers? -->\n\n'
    printf '## Notes\n\n'
    printf 'This file was generated by Power Engineer v1.4.0 SessionEnd hook.\n'
    printf 'The hook is best-effort per GitHub issues #17885 (/exit) and\n'
    printf '#6428 (/clear) — if the session exited via those commands, this\n'
    printf 'file may not have been created. In that case, rely on CLAUDE.md\n'
    printf 'proactive memory rules or the /power-engineer save-phase flow.\n'
} > "$handoff_file" 2>/dev/null; then
    log_error "failed to write handoff file: $handoff_file"
    exit 0
fi

exit 0
